Have the following links open:
- Taylor
- website on cat diagram
- `numpy.ndarray` docs : https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html


# Python review 

Short review about some core concepts in Python exemplified by objects in the NumPy library. 
Goals: 
- recall basic Python vocabulary
- practice markdown

## Libraries and packages

**library:** is a collection of code that we can use to perform specific tasks in our programs. It can be a single file or multiple ones. 

**NumPy:**  
- core library for numerical computing in Python. 
- many of the libraries use NumPy's arrays as their building blocks
- computations on NumPy objects are optimized for speed and memory usage

Let's import NumPy using the **standard to abbreviation** `np`:

In [6]:
import numpy as np

*By importing `numpy`, all the objects and functions in this library will be available for us to use in our notebook.*

## Variables

**variable:** a name we assign to a particular object in Python. 

Example:

In [7]:
# Assign a small array to variable a
a = np.array([[1,1,2],[3,5,8]])

*When we run the cell, we store the variables and their value.*

To view a variable's value from within our Jupyter notebook:

In [8]:
# Run cell with the variable name to show value
a

array([[1, 1, 2],
       [3, 5, 8]])

In [9]:
# Use `print` function to print the value
print(a)

[[1 1 2]
 [3 5 8]]


*Comments should start with a capital letter.*

## R and Python: assigning values

Remember that in Python we use the equal sign `=` to assign values to variables in the same way the left-arrow `<-` is used in R:
``` R
# R: assign value 10 to variable a
a <- 10
```

``` R
# Python: assign value 10 to variable a
a = 10
```
## Convention: Use `snake_case` for naming variables

There are many ways of constructing multi-word variable names. 

In this course we will name variables using **snake_case**, where words are all in small caps and separated by underscores (ex: `raw_data`, `fires_2023`). 

*This is the naming convention suggested by the PEP 8 - Style Guide for Python Code*

**Remember variable names should be both descriptive and concise!**

## Objects

**object:** (informally speaking) is a bundle of *properties* and *actions* about something specific. 

Example:

Object: data frame
Properties: number of rows, names of columns, and date created
Actions: selecting a specific row or adding a new column. 

A variable is the name we give a specific object, and the same object can be referenced by different variables. 

*Analogy: Sun (object) is called "sol" in Spanish and "soleil" in French, so two different names (variables) represent the same object.*

In practice, we can often use the word variable and object interchangeably.

*I want to bring up what objects are so you are not caught off-guard with vocabulary you will often encounter in the documentation, StackExchange, etc.*

## Types

Every object in Python has a **type**, the type tells us what kind of object it is. We can also call the type of an object, the **class** of an object, so class and type both mean what kind of object we have. 


In [10]:
print(a)
# See the type/class of a variable/object by using the `type` function
type(a)

[[1 1 2]
 [3 5 8]]


numpy.ndarray

The `numpy.ndarray` is the core object/data type in the NumPy package.

In [11]:
print(a[0,0])

# Check the type of an entry in the array by indexing
type(a[0,0])

1


numpy.int64

Notice the type of the value 1 in the array is `numpy.int64` and not just the standard Python integer type `int`. 

The NumPy type `numpy.int64` is telling us 1 is an integer stored as a 64-bit number. 

*NumPy has its own data types to deal with numbers depending on memory storage and floating point precision*

## R and Python: indexing

Remember that **in Python the indexing starts from 0, while in R it starts from 1**. 

*If you learned R first, this might seem odd but it's easy to get used to it with some practice.*

A way to understand this 0-indexing is that, in Python, the index indicates the *displacement* from the start of the collection. So '0 index in an array' means 'zero displacement from the start of the array', in other words, the first element of the array. 

## Check-in
How would you access the value 5 in the array `a`?


*Since "everything in Python is an object" and every object belongs to a class, we will interact with SO MANY classes in this course.*

*Often, knowing the type of an object is the first step to finding information to code what you want!*

## Functions

`print` was our first example of a Python **function**. 

Functions take in a set of **arguments**, separated by commas, and use those arguments to create an **output**. 

In this course we will use argument and parameter interchangeably. They do, however, have related but different meanings. 

We can ask for information about what a function does function by executing `?` followed by the function name:

In [12]:
?print

Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
Docstring:
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.
end
  string appended after the last value, default a newline.
file
  a file-like object (stream); defaults to the current sys.stdout.
flush
  whether to forcibly flush the stream.
Type:      builtin_function_or_method

![](/book/images/lesson-1/print-docstring.png)

What we obtain is a **docstring**, a special type of comment that is used to document how a function (or class, or module) works. 

*first line in the docstring: is telling us the function name followed by all of its arguments in parentheses.*

*Then there is a short description of what the function does.*

*And finally a list of the arguments and a brief explanation about each of them.*

You can see there are different types of arguments inside the function's parenthesis. Roughly speaking, a function has two types of arguments:

- **non-optional arguments**: arguments *you* need to specify for the function to do something, and

- **optional arguments**: arguments that are pre-filled with a default value by the function, but you can override them. Optional arguments appear inside the parenthesis () in the form `optional_argument = default_value`. 

Example:

`end` is a parameter in `print` with the default value a new line. 
We can pass the value ` ^_^` to this parameter so that finishes the line with ` ^_^` instead:

In [13]:
print('changing the default end argument of the print function', end=' ^_^')

changing the default end argument of the print function ^_^

*Notice that before we had always used print without specifying any value for the `end` parameter.*


## Attributes & methods

An object in Python has attributes and methods. 

- **attribute:** a property of the object, some piece of information about it.
- **method:** a procedure associated with an object, so it is an action where the main ingredient is the object. 

For example, these could be some attributes and methods for class `cat`:

- class: cat
- attributes: name, color, age, weight
- methods: meow(), nap(), chase_lasers(), move_tail()


More formally, **a method is a function** that acts on the object it is part of.

We can access a variable's attributes and methods by adding a period `.` at the end of the variable's name. So we would write `variable.variable_method()` or `variable.variable_attribute`. 

## Check-in
Suppose we have a class `fish`, make a diagram similar to the `cat` class diagram showing 3 attributes for the class and 3 methods.

Examples of attributes:

NumPy arrays have many methods and attributes. Let's see some concrete examples.

In [14]:
# A 3x3 array
var = np.array([[1,2,3],[4,5,6],[7,8,9]])
var

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

`T` is an example of attribute, it returns the transpose of `var`:

In [15]:
print(var.T)
print(type(var.T))

[[1 4 7]
 [2 5 8]
 [3 6 9]]
<class 'numpy.ndarray'>


`shape`, another attribute, tells us the shape of the array:

In [16]:
print(var.shape)
print(type(var.shape))

(3, 3)
<class 'tuple'>


`ndim` is an attribute holding the number of array dimensions

In [27]:
print('dim:', var.ndim, '| type:', type(var.ndim))

dim: 2 | type: <class 'int'>


Notice these attributes can have many different data types. 

Examples of methods:

The `tolist` method returns the array as a nested list of scalars:

In [18]:
var.tolist()

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

The `min` method returns the minimum value in the array along a specified axis:

In [19]:
var.min(axis=0)

array([1, 2, 3])

## Check-in

We can also call the `min` method without any parameters:

In [20]:
var.min()

1

What kind of parameter is `axis` in our previous call of the `var` method?
:::

Remember, methods are functions associated to an object. We can confirm this!

In [21]:
type(var.tolist)

builtin_function_or_method

In [22]:
type(var.min)

builtin_function_or_method

You can see a complete list of [NumPy array's methods and attributes](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html) in the documentation.


*Optional*
## R and Python: are there methods in R?

It is uncommon to use methods within an object in R. Rather, functions are extrinsic to the objects they are acting on.  In R, for example, there would usually be two separate items: the variable `var` and a separate function `min` that gets `var` as a parameter:

``` R
# This is R code
var <- array(c(1,4,7,2,5,8,3,6,9), dim =c(3,3))
min(var)
```

Using the pipe operator `%>%` in R's tidyverse is closer to the dot `.` in Python:

``` R
# This is R code
var <- array(c(1,4,7,2,5,8,3,6,9), dim =c(3,3))
var %>% min()
```

What happens here is that the pipe `%>%` is passing `var` to the `min()` function as its first argument. This is similar to what happens in Python when a function is a method of a class:

``` python
# This is Python code
var = np.array([[1,2,3],[4,5,6],[7,8,9]])
var.min()
```

When working in Python, remember that *methods are functions that are part of an object* and a method uses the object it is part of to produce some information.

## Exercise
1. Read the `print` function help. What is the type of the argument `sep`? Is this a default or non-default argument? Why?

2. Create two new variables, one with the integer value 77 and another one with the string 99.

3. Use your variables to print `77%99%77` by changing the value of one of the default arguments in `print`.

In [23]:
x = 77
y = '99'
print(x,y,x,sep='%')

77%99%77
